heat_template_version: 2014-10-16

description: >
  CADF configuration bug workaround

parameters:
  servers:
    type: json
  DeployIdentifier:
    type: string

resources:
  CustomExtraConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/sh
        set -x
        if [[ `hostname` = *"lab-ctl-"* ]]; then
            sed -i 's/driver[\t ]*=[\t ]*messaging,log/driver = messaging\ndriver = log/' /etc/keystone/keystone.conf
            systemctl restart httpd.service
            crudini --del /usr/share/neutron/neutron-dist.conf DEFAULT notification_driver
            systemctl list-unit-files | awk '/neutron.*enabled/ && $1 !~ /cleanup/ { print $1; }' | xargs systemctl restart
        fi

  CustomExtraDeployments:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: servers}
      config: {get_resource: CustomExtraConfig}
      actions: ['CREATE','UPDATE']
      input_values:
        deploy_identifier: {get_param: DeployIdentifier}
